version: 0.2

phases:
  install:
    commands:
      - echo "start"
      - DATETIME=`date "+%Y%m%d%H%M"`
      - echo $DATETIME
      - echo $TEST
      - npm install
  pre_build:
    commands:
      - npm run test
      - rm -rf ./__tests__
      - npm prune --production
  build:
    commands:
      - sam deploy --config-file samconfig.toml  --parameter-overrides ZipFileBucket=lambda-cicd-test ZipFileKey=${DATETIME}.zip
artifacts:
  type: zip
  files:
    - template-export.yml
